name: Build and Push Release

on:
  push:
    tags:
      - '*'   # Match all tags

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          DOCKER_BUILDKIT=1 docker build --build-arg BUILD_TYPE=Release -t ghcr.io/${{ github.repository }}/devops-task-ccp-release:latest .

      - name: Run container for final checks
        run: docker run --rm ghcr.io/${{ github.repository }}/devops-task-ccp-release:latest /bin/sh -c "chmod +x /project/build/Release/hello_main && /project/build/Release/hello_main"

      - name: Push Docker image to GitHub Container Registry
        # Only run this step if the event is a tag push
        if: startsWith(github.ref, 'refs/tags/')
        run: docker push ghcr.io/${{ github.repository }}/devops-task-ccp-release:latest